/*
OPERADORES DE COMPARAÇÃO
> MAIOR QUE
>= MAIOR QUE OU IGUAL A
< MAIOR QUE 
<= MENOR QUE OU IGUAL A
== IGUALDADE(VALOR) *NÃO RECOMENDADO*
=== IGUALDADE (VALOR E TIPO)
!= DIFERENTE (VALOR) **
!== DIFERENTE (VALOR E TIPO)

*/

